/**
 * Build src/data/places.json from src/places/*.md (read-only).
 * Never writes into src/places/.
 *
 * Townland: blank in MD → point-in-polygon; non-empty → override.
 * Drafts excluded from public JSON.
 */
const fs = require("fs");
const path = require("path");
const {
  ROOT,
  loadCategories,
  normalizeCategory,
  resolveTownland,
  listPlaceFiles,
  readPlaceFile,
  isPublishedStatus,
  assertNoWriteToPlaces,
} = require("./lib/place-utils");

const OUT_JSON = path.join(ROOT, "src", "data", "places.json");

function firstHero(data) {
  if (data.heroImage) return String(data.heroImage);
  const images = data.images;
  if (!Array.isArray(images) || !images.length) return null;
  const first = images[0];
  if (typeof first === "string") return first;
  return first.path || first.src || null;
}

function normalizeImages(data) {
  const out = [];
  if (Array.isArray(data.images)) {
    for (const img of data.images) {
      if (typeof img === "string") {
        out.push({ path: img, caption: "", credit: "" });
      } else if (img && (img.path || img.src)) {
        out.push({
          path: img.path || img.src,
          caption: img.caption || "",
          credit: img.credit || "",
        });
      }
    }
  }
  if (!out.length && data.heroImage) {
    out.push({
      path: String(data.heroImage),
      caption: data.heroCaption || "",
      credit: data.credit || "",
    });
  }
  return out;
}

function main() {
  assertNoWriteToPlaces(OUT_JSON); // ensure helper works; OUT_JSON is outside places
  const placesRoot = path.join(ROOT, "src", "places");
  // Belt-and-braces: refuse if someone points OUT at places
  if (path.resolve(OUT_JSON).startsWith(path.resolve(placesRoot) + path.sep)) {
    throw new Error("Internal error: output path inside src/places/");
  }

  const { byId } = loadCategories();
  const published = [];

  for (const filePath of listPlaceFiles()) {
    const { data, body } = readPlaceFile(filePath);
    if (!isPublishedStatus(data.status)) continue;

    const id = String(data.id || "").trim();
    const name = String(data.name || data.title || id).trim();
    const lat = parseFloat(data.lat);
    const lng = parseFloat(data.lng);
    if (!id || !Number.isFinite(lat) || !Number.isFinite(lng)) continue;

    const category = normalizeCategory(data.category) || "unknown";
    const catMeta = byId[category];
    const town = resolveTownland(data, lat, lng);
    const images = normalizeImages(data);
    const heroImage = firstHero(data);
    const layer =
      data.layer || (category === "exhibit" ? "mtu" : "places");

    const categories = Array.isArray(data.categories)
      ? data.categories.map(normalizeCategory)
      : [category];

    published.push({
      id,
      name,
      location: { lat, lng },
      category,
      categoryLabel: (catMeta && catMeta.label) || category,
      categoryColour: (catMeta && catMeta.colour) || "#6B7280",
      categoryOther: data.categoryOther || "",
      categories,
      eras: Array.isArray(data.eras) ? data.eras : [],
      preview: data.preview || "",
      author: data.author || "",
      status: data.status || "published",
      layer,
      liveVideoPage: data.liveVideoPage || null,
      credit: data.credit || null,
      youtube: data.youtube || "",
      townland: town.townland,
      townlandIrish: town.townlandIrish,
      townlandSource: town.townlandSource,
      heroImage,
      heroAlt: data.heroAlt || name,
      images,
      sources: Array.isArray(data.sources) ? data.sources : [],
      hasPreview: !!(data.preview && String(data.preview).trim()),
      hasBody: !!(body && body.length > 40),
      detailPath: data.detailPath
        ? String(data.detailPath).trim()
        : `/map/places/${id}/`,
    });
  }

  published.sort((a, b) => a.name.localeCompare(b.name));

  const payload = {
    $comment:
      "Generated by scripts/build-places.js from src/places/*.md — do not edit by hand. Townland blank in MD = auto from polygons.",
    places: published,
  };

  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, JSON.stringify(payload, null, 2) + "\n", "utf8");
  console.log(
    `Wrote ${published.length} published places → ${path.relative(ROOT, OUT_JSON)}`
  );
}

main();
