/**
 * Published places for templates (map list). Regenerated by npm run build-places.
 */
const fs = require("fs");
const path = require("path");

const file = path.join(__dirname, "..", "data", "places.json");
if (!fs.existsSync(file)) {
  module.exports = [];
} else {
  const raw = JSON.parse(fs.readFileSync(file, "utf8"));
  module.exports = raw.places || [];
}
